version = 0.1
[default.deploy.parameters]
stack_name = "csv-analyzer"
resolve_s3 = true
s3_prefix = "csv-analyzer"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" CorsOrigin=\"*\""
image_repositories = []
